package analizadorSintactico;

public enum noTerminales {
	RES_LISTA_LLAMADA, L_PARAMS_LLAMADA, REXP3_2, REXP3, LISTA_EXP, EXP3, OP_SELECCION, REXP2, EXP2, OP_INC, 
	OP_UNARIOS, EXP1, OP_MULT, REXP_MULT, EXP_MULT, OP_AD, REXP_AD, EXP_AD, OP_DESPL, REXP_DESPL, EXP_DESPL,
	OP_COMP, REXP_COMP, EXP_COMP, OP_REL, REXP_REL, EXP_REL, REXP_ANDB, EXP_ANDB, REXP_XORB, EXP_XORB, REXP_ORB,
	EXP_ORB, REXP_ANDL, EXP_ANDL, REXP_ORL, EXP_ORL, REXP_COND, EXP_COND, REXP, EXP, CONSTANTE, CASE, RCASES2,
	RCASES, CASES, L_CASES, SENTENCIA_CASE, RSENTENCIA_ASIG, OP_ASIG, SENTENCIA_ASIG, CAMPO, SENTENCIA_BUCLE,
	SENTENCIA_ELSE, RSENTENCIA_IF, SENTENCIA_IF, RSCANF2, RSCANF, RPRINTF2, INDIRECCION, REFERENCIA, RPRINTF,
	ENTRECOMILLADO, OTRAS_SENTENCIAS, SENTENCIA, BLOQUE_SENTENCIAS, L_SENTENCIAS, RTIPO2, TIPO_PRIMITIVO,
	MODIFICADOR, RTIPO, TIPO, RL_PARAMS2, RL_PARAMS, L_PARAMS, RDEF_FUNCION, RDEF_TYPEDEF, DEFINICION_TYPEDEF,
	DEF_VAR, L_VARIABLES, DEFINICION_STRUCT, RENUM2, RENUM, DEFINICION_ENUM, CONTENIDO, CORCHETES, LISTA_IDENS,
	DEFINICION_UNION, RIFDEF2, RIFDEF, RMACRO, MACROS, RDEF_VARIABLE2, RDEF_VARIABLE, RDEFINICION2, RDEFINICION,
	DEFINICION, DEFINICION_GLOBAL, L_DEFINICIONES, PROGRAMA
}